### ISSUE TITLE
Heroku buildpack fails with apps generated by Amber-cli v0.6.5 or newer

### ISSUE THREAD

**Issue by jhonnold** [amberframework/heroku-buildpack-amber#7]
In version 0.6.5 and later it seems that the shard.yml auto adds amber to its target list.

```
targets:
  test:
    main: src/test.cr

  amber:
    main: lib/amber/src/amber/cli.cr
```

In this build-pack, when detecting the targets, it finds amber and then tries to build `src/amber.cr` which does not exist.

```
for target in $(compgen -A variable | grep shard_targets | sed 's/shard_targets_\(.*\)_main/\1/g'); do
  start "Building src/${target}.cr (auto-detected from shard.yml)"
    AMBER_ENV=production crystal build --release --no-debug $BUILD_DIR/src/${target}.cr -o $BUILD_DIR/bin/${target}
    chmod +x $BUILD_DIR/bin/${target}
  finished
done
```
